### ISSUE TITLE
[상점페이지] 상점페이지 추가

### ISSUE THREAD

**Issue by daepan** [BCSDLab/KOIN_WEB_RECODE#13]
## Feature Name
상점페이지 구현

## Progress

- [x] 상점리스트 react-query 적용하기
- [x] 검색기능추가
- [x] 상점 페이지 구현
- [x] 상점 라우트 작성
- [x] 카테고리 목록 중 ALL 생성
- [x] scss import => use로 변경

## Design Screenshot
<img width="1440" alt="스크린샷 2022-08-31 오후 9 01 12" src="https://user-images.githubusercontent.com/50792467/187673934-ca3ca218-3600-44b0-8805-9db816053c4b.png">

**Comment by SimYunSup** [comment]
1. 상점 리스트를 recoil로 저장하는 이유라도 알 수 있을까요?
2. 카테고리 모두를 추가해 달라는 요청도 있어 고려해주시길 바랍니다.

**Comment by daepan** [comment]
1. 과거 코인에서는 스토어에 저장해둔 상태에서 불러오는 방식을 채택했는데, 그 이유는 서버에서 카테코리별 메뉴를 불러올 수 도 없기에 해당 부분을 한번에 불러오고 유지하는 것이 좋을 것 같다고 생각했습니다.
2. 카테고리 모두 추가라고 하시면 ALL 이라는 카테고리바에 아이콘이 필요하다는 말씀이신가요?

**Comment by SimYunSup** [comment]
@daepan 
1. 특별한 상황이 아닌 이상 리액트 쿼리로 서버 데이터를 받아야 합니다.
2. 네
