### ISSUE TITLE
[버스 페이지] 시간 표시 오류

### ISSUE THREAD

**Issue by ChoiWonBeen** [BCSDLab/KOIN_WEB_RECODE#38]
## Describe the bug

`busModules.ts`의 `getStartTimeString` 함수는 API의 Response로 받아오는 `remain_time`을 기준으로 도착 시간을 계산합니다.
초,분,시 계산 과정에서 오류가 있는지 간헐적으로 도착 시간이 1분씩 미뤄지는 버그가 있습니다.

또한 59초 -> 00초로 변경되는 시점에 도착 시간이 01분으로 튀는 현상이 발생합니다.

## Screenshot
![image](https://user-images.githubusercontent.com/50780281/227761403-e5bb457a-dc0b-48b4-bdd0-387bd381f01c.png)
![image](https://user-images.githubusercontent.com/50780281/227761405-30c5051c-96ae-455d-9b0d-8ed2775152f6.png)

**Comment by SimYunSup** [comment]
@ChoiWonBeen @haejinyun  해당 문제는 초를 구분하지 않는 필터링 방식을 그대로 가져온 것때문에 나타난 것으로 보입니다. 직접 계산하지 말고 Date객체를 통해 milisecond를 전달하여 계산을 맡기는 형식으로 진행해야 할 것 같습니다.
