### ISSUE TITLE
[Auth] 로그인 화면 및 인증 부분 추가

### ISSUE THREAD

**Issue by SimYunSup** [BCSDLab/KOIN_WEB_RECODE#5]
## Feature Name

로그인 화면 및 인증 로직 추가

## Progress

- [x] 기본 axios wrapper 추가
- [x] 인증 로직 추가
  - [ ] 로그인 / 로그아웃 / 회원가입 / 비밀번호 찾기에 대한 React-Query 추상화 
- [x] 로그인 화면 추가
  - [x] React-Router의 구조 잡기 - App.js에서. 아마 pages 폴더로 분리 예정
## Design Screenshot

![image](https://user-images.githubusercontent.com/47362439/181468113-ca4b45d9-2a25-4e1f-a202-fce6093f9ce1.png)

## Precautions

- 인증로직은 거의 모든 부분에서 사용합니다. 신중히 만들어주세요.
- 로그인 화면은 헤더가 없습니다. header를 `display:none`으로 없애지 마세요.

**Comment by SimYunSup** [comment]
참고할만한 Auth Flow에 대한 생각입니다.

이를 참고해서 어느 storage에 저장할지 comment로 달아주세요.

## Authorization flow with JWT

인가 플로우에 대한 논쟁은 오랜 시간을 거쳐 진행되어 오고 있다.

그 이유는 잘 알고 있는 두 가지 해킹 위험이다.

1. XSS (교차 사이트 스크립팅)
2. XSRF (사이트 간 요청 위조)

두개의 해킹 위험을 방지한 인가를 하기 위해 여러가지 방법을 사용할 수 있다.

- refresh token
  1. SameSite, HttpOnly 쿠키에 저장
      - SSR일 경우에는 proxy 설정 or 또 다른 Cookie 설정을 해주어야 한다.
      - [BFF(Backend For Frontend)](https://dev.to/damikun/web-app-security-understanding-the-meaning-of-the-bff-pattern-i85)를 사용하면 되긴 하지만.. 비용이 추가로 발생한다.
      - FrontEnd가 Web이 아닐경우 추가 로직이 필요하다.
  2. localStorage에 저장
      - OWASP 보안 지침에 위배된다.
      - 하지만 "로그인 상태 유지"를 위해 결국 필요하다(쿠키를 써도 되긴 한다).
        - 아직도 논쟁 대상에 있다. 
      - refresh token의 유효함을 검사하기 위해 추가 로직이 필요하다.
  3. sessionStorage에 저장
      - 로그인 상태 유지, 탭 간 인가 공유가 불가하다.
- access token
  1. SameSite, HttpOnly 쿠키에 저장
  2. sessionStorage에 저장
      - access token의 유효함을 검사하기 위해 추가 로직이 필요하다(물론 한 번 요청 하기만 하면 되지만 인터넷이 느리다면?).
  3. JS 변수 내에 저장
      - 새로고침 할 때마다 access token을 새로 요청해야 한다.

나만의 결론을 내리자면 refresh token을 쓸 때는 localStorage, access token을 쓸 때는 sessionStorage를 사용하는 것이다. 강화된 쿠키를 쓰지 않는 이유는 쿠키 때문에 더 작성하는 로직이 localStorage보다 많다고 생각하기 때문이다(그냥 쿠키를 쓰지 않는 이유는 XSRF 때문이다).

> [출처](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.md#token-storage-on-client-side)

> 추가: 쿠키와 함께 [CORS](https://developer.mozilla.org/ko/docs/Web/HTTP/CORS) 요청을 하려면 [Credentials 설정](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials)을 추가해야 한다.

**Comment by SimYunSup** [comment]
@daepan 이 2022.08.20 을 목표로 할 예정입니다.

**Comment by daepan** [comment]
현재 로그인 방식에 대해 고민하고 있습니다. 현 코인에 대해서 로그인 이후 token 하나만을 가지고 있습니다. 전 리코드 전에는 세션스토리지에 보관하는 방식이며, 저장되는 것은 유저정보와 토큰입니다.
저의 생각에서는 이것을 js 코드로 유지한다는 처음 생각했지만 token이 하나 밖에 존재하지않아 refresh 토큰에 대한 처리가 불가능해 로그인 유지가 어려울 것 같습니다.
제 생각에는 이번에 로컬스토리지에 저장하는 방식으로 하는 것이 좋지 않을 까 생각합니다. 로컬에 있다면 token에 대한 유무를 전역상태로 굳이 취급하지 않아도 되고 로컬에 token만 저장해둔다면 코인 페이지에 대한 사용성 증대 및 로그인 상태 관리가 훨씬 유용할 것이라고 생각됩니다.
다른 여러분들의 생각이 궁금합니다.
